apiVersion: kubeci.kube.ci/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wf-template
  namespace: default
spec:
  steps:
  - name: step-echo-${#count}
    image: ${image}
    commands:
    - ${shell}
    args:
    - -c
    - ${cmd}
  parameters:
  - key: count
    default: asdf
  - key: image
    default: busybox
  - key: shell
    default: sh
  - key: cmd

# https://github.com/drone/envsubst/blob/master/eval_test.go