apiVersion: engine.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: wf-test
  namespace: default
spec:
  allowForceTrigger: true
  triggers:
  - apiVersion: v1
    kind: ConfigMap
    resource: configmaps
    namespace: default
    name: my-config
    onCreateOrUpdate: true
    onDelete: false
    envFromPath:
      META_NAME: '{$.data.hello}'
  serviceAccount: wf-sa
  template:
    name: wf-template
    arguments:
      image: alpine
      cmd: echo $META_NAME
  excutionOrder: Serial
