apiVersion: v1
kind: Service
metadata:
  name: kubeci-engine-dev-apiserver
  namespace: ${KUBECI_ENGINE_NAMESPACE}
  labels:
    app: kubeci-engine-dev-apiserver
spec:
  ports:
  - name: api
    port: 443
    protocol: TCP
    targetPort: 6443
  type: ClusterIP
---
# To get to the host machine from the VM,
# the IP is 10.0.2.2 (by convention)
# ref: https://stackoverflow.com/questions/9537751/virtualbox-port-forward-from-guest-to-host
apiVersion: v1
kind: Endpoints
metadata:
  name: kubeci-engine-dev-apiserver
  namespace: ${KUBECI_ENGINE_NAMESPACE}
  labels:
    app: kubeci-engine-dev-apiserver
subsets:
- addresses:
  # list all external ips for this service
  - ip: 10.0.2.2
  ports:
  - name: api
    port: 6443
    protocol: TCP
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.admission.engine.kube.ci
  labels:
    app: kubeci-engine-dev-apiserver
spec:
  insecureSkipTLSVerify: true
  group: admission.engine.kube.ci
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: kubeci-engine-dev-apiserver
    namespace: ${KUBECI_ENGINE_NAMESPACE}
  version: v1alpha1
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.extension.kube.ci
  labels:
    app: kubeci-engine-dev-apiserver
spec:
  insecureSkipTLSVerify: true
  group: extension.kube.ci
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: kubeci-engine-dev-apiserver
    namespace: ${KUBECI_ENGINE_NAMESPACE}
  version: v1alpha1
