apiVersion: kubeci.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: workflow-git-branch
  namespace: default
spec:
  steps:
  - args:
    - -c
    - touch /kubeci/file-1
    commands:
    - sh
    image: alpine
    name: step-1
  - args:
    - -c
    - touch /kubeci/file-2
    commands:
    - sh
    dependency:
    - step-1
    image: alpine
    name: step-2
  - args:
    - -c
    - touch /kubeci/file-3
    commands:
    - sh
    dependency:
    - step-1
    image: alpine
    name: step-3
  - args:
    - -c
    - touch /kubeci/file-4
    commands:
    - sh
    dependency:
    - step-2
    - step-3
    image: alpine
    name: step-4
  - args:
    - -c
    - echo step-5; ls /kubeci
    commands:
    - sh
    dependency:
    - step-1
    - step-4
    image: alpine
    name: step-5
  triggers:
  - apiVersion: git.kube.ci/v1alpha1
    kind: Branch
    name: master
    namespace: default
    onAddOrUpdate: true
    onDelete: false
    resource: branches
    selector:
      matchLabels:
        repository: watch

