apiVersion: kubeci.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: wf-json-path
  namespace: default
spec:
  triggers:
  - apiVersion: v1
    kind: ConfigMap
    resource: configmaps
    namespace: default
    name: my-config
    onCreateOrUpdate: true
    onDelete: false
    envFromPath:
      META_NAME: '{$.metadata.name}'
  serviceAccount: default
  steps:
  - name: step-echo
    image: alpine
    commands:
    - sh
    args:
    - -c
    - echo $META_NAME
