apiVersion: engine.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: wf-cred
  namespace: default
spec:
  allowForceTrigger: true
  triggers:
  - apiVersion: v1
    kind: ConfigMap
    resource: configmaps
    namespace: default
    name: my-config
    onCreateOrUpdate: true
    onDelete: false
  serviceAccount: wf-sa
  executionOrder: Serial
  steps:
  - name: step-ls-home
    image: alpine
    commands:
    - sh
    args:
    - -c
    - ls -laR $HOME
  - name: step-clone
    image: alpine/git
    commands:
    - sh
    args:
    - -c
    - ln -s $HOME/.ssh /root/.ssh; git clone git@github.com:diptadas/kubeci-gpig.git
    # HACK: https://github.com/knative/build/blob/master/cmd/git-init/main.go#L59
  - name: step-ls-repo
    image: alpine
    commands:
    - sh
    args:
    - -c
    - ls -la kubeci-gpig
