apiVersion: kubeci.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: wf-cred
  namespace: default
spec:
  allowForceTrigger: true
  triggers:
  - apiVersion: v1
    kind: ConfigMap
    resource: configmaps
    namespace: default
    name: my-config
    onCreateOrUpdate: true
    onDelete: false
  serviceAccount: wf-sa
  steps:
  - name: step-echo
    image: alpine
    commands:
    - sh
    args:
    - -c
    - ls -laR $HOME
