apiVersion: engine.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: wf-implicit
  namespace: default
spec:
  allowForceTrigger: true
  triggers:
  - apiVersion: v1
    kind: ConfigMap
    resource: configmaps
    namespace: default
    name: my-config
    onCreateOrUpdate: true
    onDelete: false
  serviceAccount: wf-sa
  excutionOrder: Serial
  steps:
  - name: step-echo
    image: alpine
    commands:
    - sh
    args:
    - -c
    - pwd; echo $HOME # print working-dir and $HOME
  - name: step-ls
    image: alpine
    commands:
    - sh
    args:
    - -c
    - ls -laR /test-volume
    volumeMounts: # explicit volume mounts
    - name: test-volume
      mountPath: /test-volume
  volumes: # explicit volumes
  - name: test-volume
    hostPath:
      path: /tmp
      type: Directory