apiVersion: v1
kind: ServiceAccount
metadata:
  name: wf-sa
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: wf-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wf-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: wf-sa
  namespace: default
roleRef:
  kind: Role
  name: wf-role
  apiGroup: rbac.authorization.k8s.io