apiVersion: kubeci.kube.ci/v1alpha1
kind: Workflow
metadata:
  name: wf-parallel
  namespace: default
spec:
  allowForceTrigger: true
  triggers:
  - apiVersion: v1
    kind: ConfigMap
    resource: configmaps
    namespace: default
    name: my-config
    onCreateOrUpdate: true
    onDelete: false
    envFromPath:
      META_NAME: '{$.data.hello}'
  serviceAccount: wf-sa
  executionOrder: parallel
  steps:
  - name: step-01
    image: alpine
    commands:
    - sh
    args:
    - -c
    - date; sleep 5s; date
  - name: step-02
    image: alpine
    commands:
    - sh
    args:
    - -c
    - date; sleep 5s; date
  - name: step-03
    image: alpine
    commands:
    - sh
    args:
    - -c
    - date; sleep 5s; date
    

