apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kubeci-engine.fullname" . }}-cleaner
  labels:
    {{- include "kubeci-engine.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    spec:
      serviceAccountName: {{ template "kubeci-engine.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
      {{- end }}
      containers:
      - name: busybox
        image: {{ .Values.cleaner.registry }}/{{ .Values.cleaner.repository }}:{{ .Values.cleaner.tag }}
        command:
          - sh
          - -c
          - "sleep 2; kubectl delete validatingwebhookconfigurations validators.engine.kube.ci || true; kubectl delete mutatingwebhookconfigurations mutators.engine.kube.ci || true"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
      restartPolicy: Never
